sudo: required
services:
  -'selenium-webdriver'

before_install:
  - wget http://chromedriver.storage.googleapis.com/2.24/chromedriver_linux64.zip

  - unzip chromedriver_linux64.zip -d /home/travis/build/RBhuyar/grocery-testNG/

  - cd /home/travis/build/RBhuyar/grocery-testNG/
  - ls -la

install: true

script:
  - mvn test
addons:
  sauce_connect:
    username: "="
    access_key: "="