sudo: required
services:
  -'selenium-webdriver'

before_install:
  - wget http://chromedriver.storage.googleapis.com/2.24/chromedriver_linux64.zip

  - unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python2.7.12/bin/

  - export CHROME_BIN=chromium-browser

install: true

script:
  - mvn test
addons:
  sauce_connect:
    username: "RBhuyar"
    access_key: "09fea2fb-94b7-4093-b714-e9fda7c80b6f"