sudo: required
services:
  -'selenium-webdriver'
env:
 - SKIP_LOCAL_BROWSERS=true
addons:
  sauce_connect:
    username: {$username}
    access_key: {$access_key}
    apt:
      sources:
        - google-chrome
      packages:
        - google-chrome-stable

before_install:
  - wget http://chromedriver.storage.googleapis.com/2.26/chromedriver_linux64.zip

  - unzip chromedriver_linux64.zip -d /home/travis/build/RBhuyar/grocery-testNG/


install: true

script:
  - mvn test