sudo: required
services:
  -'selenium-webdriver'

before_install:
  - wget http://chromedriver.storage.googleapis.com/2.26/chromedriver_linux64.zip

  - unzip chromedriver_linux64.zip -d /home/travis/build/RBhuyar/grocery-testNG/


install:
  - xvfb-run wct --skip-plugin local

script:
  - mvn test
env:

addons:
  sauce_connect:
    username: "RBhuyar"
    access_key: "09fea2fb-94b7-4093-b714-e9fda7c80b6f"
    apt:
      sources:
        - google-chrome
      packages:
        - google-chrome-stable