sudo: required
services:
  -'selenium-webdriver'

before_install: true
install: true

script:
  - mvn test
addons:
  sauce_connect:
    username: "RBhuyar"
    access_key: "09fea2fb-94b7-4093-b714-e9fda7c80b6f"